# -*- coding: utf-8 -*-
"""suc_ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEec7ftqg9w3C7fZ-wEXBOI_ZLfMWeij
"""



"""https://github.com/fabriziosalmi/pdf-ocr"""

!sudo apt-get update && sudo apt-get install tesseract-ocr libtesseract-dev tesseract-ocr-all

!sudo apt-get update && sudo apt-get install poppler-utils

!git clone https://github.com/fabriziosalmi/pdf-ocr.git

# Commented out IPython magic to ensure Python compatibility.
# %cd pdf-ocr

!python install_dependencies.py

!python app.py



https://nodejs.org/docs/latest/api/synopsis.html
!pip install pyngrok



from pyngrok import ngrok
import threading
import time

ngrok_token = "XXXXXXXXXXXXXXXXXXXXXXXXX"
ngrok.set_auth_token(ngrok_token)

# Start ngrok in a separate thread to avoid blocking
def start_ngrok():
    public_url = ngrok.connect(3000).public_url
    print(f"🚀 Ngrok Tunnel Open: {public_url}")

ngrok_thread = threading.Thread(target=start_ngrok)
ngrok_thread.start()

# Wait for ngrok to start (optional)
time.sleep(5)

# Execute your node.js script
!node hello-world.js

!pip install pyngrok

from pyngrok import ngrok
import threading
import time

ngrok_token = "XXXXXXXXXXXXXXXXXXXXXXX"
ngrok.set_auth_token(ngrok_token)

# Start ngrok in a separate thread to avoid blocking
def start_ngrok():
    public_url = ngrok.connect(8011).public_url
    print(f"🚀 Ngrok Tunnel Open: {public_url}")

ngrok_thread = threading.Thread(target=start_ngrok)
ngrok_thread.start()

# Wait for ngrok to start (optional)
time.sleep(5)

!python app.py